BOUNDING_COLOR = (0, 255, 0)
HEIGHT_OFFSET = 384
WIDTH_OFFSET = 640
ABOVE_BELOW_SPLIT = 515
NUMBER_OF_SAMPLES_BEFORE_UPLOAD = 20
SAMPLE_POLLING_TIME = 2
DETECTION_ACCURACY = 0.5
TOOLS_LIST = [
    "Anvil",
    "Aviation_Snip",
    "Bench_Vise",
    "Brush",
    "Caliper",
    "Caulk_Gun",
    "Chisel",
    "Clamp",
    "Drill",
    "File",
    "Flashlight",
    "Gloves",
    "Grinder",
    "Hammer",
    "Hex_Key",
    "Hole_Punch",
    "Knife",
    "Level",
    "Mallet",
    "Marker",
    "Meter",
    "Pen",
    "Pencil",
    "Pencil_Sharpener",
    "Plane",
    "Pliers",
    "Putty_Knife",
    "Rake",
    "Ratchet",
    "Riveter",
    "Safety_Glass",
    "Safety_Helmet",
    "Safety_Mask",
    "Safety_Headphones",
    "Saw",
    "Scissors",
    "Screwdriver",
    "Soldering_Iron",
    "Spade",
    "Square",
    "Staple_Gun",
    "Stapler",
    "Tape",
    "Tape_Dispenser",
    "Trowel",
    "Wrench",
    "Ruler",
    "Crowbar",
    "Axe",
    "Allen keys",
    "Clampingtool",
    "Crimpingtool",
    "Levelingtool",
    "Measuringtool",
    "Screws",
]
